domain_path: C:\Users\nicol\usb_uart_test\platform\export\platform\sw\standalone_ps7_cortexa9_1
app_src_dir: C:\AMDDesignTools\2025.2\Vitis\data\embeddedsw\lib\sw_apps\lwip_echo_server
template: lwip_echo_server
lang: c
